version: '3.3'

services: 
    messaging:
        image: nats-streaming:0.22.0-alpine3.13
        restart: always
        ports:
            - 4222:4222
            - 8222:8222
    
    mongo:
        image: mongo:4-bionic
        restart: always
        ports: 
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        volumes: 
            - /home/luismiguel/Documents/docker-volumes/mongodb:/data/db

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}

    interactions-messaging:
        build: interactions-messaging/.
        image: microservice-messaging:v1
        restart: always
        depends_on: 
            - messaging
            - mongo
        environment: 
            - nats_URL=${nats_URL}
            - subject_id=${subject_id}
            - MONGO_URL=${MONGO_URL}
    
    # interactions-core:
    #     build: interactions-core/.
    #     image: backend-microservice:v1
    #     restart: always
    #     depends_on: 
    #         - mongo
    #     environment: 
    #         - MONGO_URL=${MONGO_URL}
    #         - PORT=${PORT_APP}
    #     ports: 
    #         - 5000:5000